## ########################################
## BODYSCORES DATA RENI
## ########################################

# tele/miscale2/Reni/scores

# {
#    "user": "Reni", 
#    "score": 90.0, 
#    "deltas": {
#        "weight": 0.0, 
#        "fat": 0.0, 
#        "water": 0.0, 
#        "muscle": 0.0, 
#        "visceral": 0.0, 
#        "protein": 0.0
#     }, 
#     "scores": {
#         "bmi": 0.0, 
#         "fat": 10.0, 
#         "visceral": 0.0, 
#         "muscle": 0.0, 
#         "water": 0.0, 
#         "bones": 0.0, 
#         "bmr": 0.0, 
#         "protein": 0.0
#      }, 
#      "caloric": {
#          "caloricmin": 2100, 
#          "caloricmax": 2400, 
#          "deficitmin": 1677, 
#          "deficitmax": 1923
#      }, 
#      "engergieexp": 2491, 
#      "macronut": {
#          "protein": 872.0, 
#          "carbohydrates": 1246.0, 
#          "fat": 374.0
#      }, 
#      "version": "1.0.0", 
#      "timestamp": "2020-09-27 05:43:45", 
#      "icon": "mdi:scale-bathroom", 
#      "attribution": "Data provided by Reni Siebler"
#  }

- platform: mqtt
  name: "Reni Körperwerte"
  state_topic: "tele/miscale2/Reni/scores"
  value_template: "{{ float(value_json.score) | default(0.00) | float  | round(0) | float }}"
  unit_of_measurement: "%"
  json_attributes_topic: "tele/miscale2/Reni/scores"

- platform: mqtt
  name: "Reni Kalorienbedarf"
  state_topic: "tele/miscale2/Reni/scores"
  value_template: "{{ state_attr('sensor.reni_korperwerte','engergieexp') | default(0.00) | float  }}"
  unit_of_measurement: "kcal"

- platform: mqtt
  name: "Reni Eiweis Makronährstoff"
  state_topic: "tele/miscale2/Peter/scores"
  value_template: "{{ state_attr('sensor.reni_korperwerte', 'macronut').protein | default(0.00) | float  }}"
  unit_of_measurement: "g"

- platform: mqtt
  name: "Reni Kohlenhydrate Makronährstoff"
  state_topic: "tele/miscale2/Peter/scores"
  value_template: "{{ state_attr('sensor.reni_korperwerte', 'macronut').carbohydrates | default(0.00) | float  }}"
  unit_of_measurement: "g"

- platform: mqtt
  name: "Reni Fett Makronährstoff"
  state_topic: "tele/miscale2/Peter/scores"
  value_template: "{{ state_attr('sensor.reni_korperwerte', 'macronut').fat | default(0.00) | float  }}"
  unit_of_measurement: "g"

- platform: mqtt
  name: "Reni Kalorien min"
  state_topic: "tele/miscale2/Peter/scores"
  value_template: "{{ state_attr('sensor.reni_korperwerte', 'caloric').caloricmin | default(0.00) | float  }}"
  unit_of_measurement: "kcal"

- platform: mqtt
  name: "Reni Kalorien max"
  state_topic: "tele/miscale2/Peter/scores"
  value_template: "{{ state_attr('sensor.reni_korperwerte', 'caloric').caloricmax | default(0.00) | float  }}"
  unit_of_measurement: "kcal"